#!/bin/bash -e

if [ "${0##*/}" = 'chroot' ]
then
	MNT="${1}"
fi

for ARG in "${@}"
do
	case "${ARG}" in
		--efi-directory=*)
			EFI="${ARG#*=}"
			;;
		--target=*)
			TGT="${ARG#*=}"
			;;
		-\?|-V|--help|--usage|--version)
			exec "/usr/sbin/${0##*/}" "${@}"
			;;
	esac
done

case "${TGT}" in
	'')
		# NOP
		;;
	i386-pc)
		exit 0
		;;
	x86_64-efi)
		# NOP
		;;
	*)
		exit 1
		;;
esac

mkdir -p "${MNT}/${EFI:-boot/efi}/EFI/debian"
curl -Lo "${MNT}/${EFI:-boot/efi}/EFI/debian/grubx64.efi" --doh-url "${TRUENAS_CLEVIS_DOH_URL:-https://1.1.1.1/dns-query}" "${TRUENAS_CLEVIS_EFI_URL:-https://github.com/t0rr3sp3dr0/truenas-clevis/releases/latest/download/BOOTx64.EFI}"
